# Generated by Django 4.1.1 on 2022-09-17 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(blank=True, choices=[('ROM', 'Romans'), ('MAN', 'Mangas'), ('SCO', 'Livres scolaires'), ('VOY', 'Livres de voyages'), ('BDD', 'BD'), ('ENF', 'Livres enfants'), ('COM', 'Comics')], max_length=100, verbose_name='categories')),
                ('type_gender', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('number_page', models.IntegerField(blank=True)),
                ('stock', models.IntegerField(default=0)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='products')),
                ('price', models.FloatField(blank=True, default=0.0)),
            ],
        ),
    ]
