# Generated by Django 4.1.1 on 2022-09-19 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_cart_options_remove_cart_ordered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=90),
        ),
    ]
